# Generated by Django 3.0.7 on 2020-07-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StanAkcesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('nazwa', models.CharField(max_length=150)),
                ('ilosc', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
