# Generated by Django 3.1 on 2020-09-30 20:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_raportu', models.DateField(auto_now_add=True)),
                ('telefony_elza', models.IntegerField(blank=True, null=True)),
                ('telefony_stan', models.IntegerField(blank=True, null=True)),
                ('voice_elza', models.IntegerField(blank=True, null=True)),
                ('voice_stan', models.IntegerField(blank=True, null=True)),
                ('data_elza', models.IntegerField(blank=True, null=True)),
                ('data_stan', models.IntegerField(blank=True, null=True)),
                ('zdrapki_elza', models.IntegerField(blank=True, null=True)),
                ('zdrapki_stan', models.IntegerField(blank=True, null=True)),
                ('doladowania_elza', models.IntegerField(blank=True, null=True)),
                ('doladowania_stan', models.IntegerField(blank=True, null=True)),
                ('kasa_elza', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('kasa_stan', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('uzyczenie_elza', models.IntegerField(blank=True, null=True)),
                ('folia_elza', models.IntegerField(blank=True, null=True)),
                ('kto', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
