# Generated by Django 3.0 on 2020-03-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwentaryzacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='data_stan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raport',
            name='doladowania_stan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raport',
            name='kasa_stan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='raport',
            name='telefony_stan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raport',
            name='voice_stan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raport',
            name='zdrapki_stan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
